config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats 

  resources :cat_rental_requests

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  description :text             not null
#  name        :string           not null
#  sex         :string(1)        not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#



class Cat < ApplicationRecord
    require 'action_view' 
    include ActionView::Helpers::DateHelper

    COLORS = ["White", "Blue", "Black","Orange"]
    
    validates :birth_date, :color, :description, :name, :sex, presence: true
    validates :color, inclusion: { in: COLORS, message: "%{value} is not a valid color" }
    validates :sex, inclusion: { in: ["M","F"], message: "%{value} is not a valid sex"}

    has_many :cat_rental_requests, dependent: :destroy 

    def age()
        return time_ago_in_words(birth_date)+ " old"
    end



end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  end_date   :date
#  start_date :date
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  cat_id     :integer
#
# Indexes
#
#  index_cat_rental_requests_on_cat_id  (cat_id)
#
class CatRentalRequest < ApplicationRecord
    require 'action_view'
    include ActionView::Helpers::DateHelper

    STATUS = ["PENDING","APPROVED","DENIED"]

   


    validates :status, inclusion: {in: STATUS, message: "%{value} is not a valid status" }
    validates :status, :cat_id, :start_date, :end_date, presence: true 
    validate :does_not_overlap_approved_request

    belongs_to :cat  



    def overlapping_requests
        CatRentalRequest.where("cat_id = ? and start_date <= ? and end_date >= ?", self.cat_id, self.end_date, self.start_date) 
    end

    def overlapping_approved_requests
        self.overlapping_requests.where(status: "APPROVED")
    end

    def does_not_overlap_approved_request
        if overlapping_approved_requests.exists?
            errors.add(:overlapping, "Cant be overlapping with aproved rental requests")
            return false 
        end
    end
    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController


    def index 
        @cat_rental_requests = CatRentalRequest.all

        render :index
    end 

    # def show 
    #     @cat_rental_request = CatRentalRequest.find_by(id: params[:id])

    #     if @cat_rental_request 
    #         render :show 
    #     else
    #         redirect_to cat_rental_requests_url
    #     end
    # end

    def new 
        @cats = Cat.all
        @cat_rental_request = CatRentalRequest.new

        render :new 

    end

    def create 
        p rental_request_params
        @cat_rental_request = CatRentalRequest.new(rental_request_params)

        if @cat_rental_request.save 
            redirect_to cat_rental_requests_url
        else 
            puts "invalid Rental Request"
            redirect_to new_cat_rental_request_url
        end
    end


    private 

    def rental_request_params
        params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
    end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController


    def index 
        @cats = Cat.all

        render :index
    end 

    def show 
        @cat = Cat.find_by(id: params[:id])

        if @cat 
            render :show 
        else
            redirect_to cats_url
        end
    end

    def new 
        @cat = Cat.new
        @colors = Cat::COLORS

        render :new 
    end

    def create 
        p cat_params
        @cat = Cat.new(cat_params)
        

        if @cat.save 
            redirect_to @cat  
        else
            p "invaild cat!"
            redirect_to new_cat_url
        end

    end

    def edit 
        @cat = Cat.find_by(id: params[:id])
        @colors = Cat::COLORS
        render :edit 
    end

    def update 
        p cat_params
        @cat = Cat.find_by(id: params[:id])

        if @cat.update (cat_params)
            redirect_to @cat 
        else 
            p "invalid update"
            redirect_to edit_cat_url

        end
    end

    private 

    def cat_params 
        params.require(:cat).permit(:name, :sex, :color, :birth_date, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/_form.html.erb
<% action_url = (action == :new) ? cat_rental_requests_url : cat_rental_request_url(cat_rental_request) %>

<form action="<%=action_url%>" method="post">
    <% if action == :edit %>
        <input type="hidden" name="_method" value="patch">
    <% end %>

    <div>
        <label for="cat_id">Which Cat</label>
        <select name="cat_rental_request[cat_id]" id="cat_id">
            <option disabled selected>--Please Select--</option>
            <% @cats.each do |cat| %>
                <option value="<%=cat.id%>"  ><%=cat.name%> </option>

            <%end%>
        
        </select>

    </div>
    <br>
    <div>
        <label for="start_date">Start Date</label>
        <input type="date" id="start_date" name="cat_rental_request[start_date]">
    </div>
    <br>
    <div>
        <label for="end_date">End Date</label>
        <input type="date" id="end_date" name="cat_rental_request[end_date]">
    </div>


    <br>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type="submit" value="Create Cat Rental Request!">



</form>

app/views/cat_rental_requests/index.html.erb
<h1>Look at all these Cat Rentals! </h1>

    <table>
        <tr>
            <th>Cat</th>
            <th>Start Date</th>
            <th>End Date</th>
        
            <% @cat_rental_requests.order(:start_date).each do |request| %>
                <tr>
                    <td> <%= request.cat_id %> </td>  
                    <td> <%= request.start_date %> </td>  
                    <td> <%= request.end_date %> </td>   
                    <td> <%= request.status %> </td>
                </tr>           
            <% end %>
        
    </table>
<br>
<a href="<%= cats_url %>">Back to see the cats!</a>
<br>
<a href="<%= new_cat_rental_request_url %>">Make a new cat Rental Request</a>

app/views/cat_rental_requests/new.html.erb
<h1>Make a new Cat Rental Request!</h1>

<%= render "form", cat_rental_request: @cat_rental_request, cats: @cats, action: :new%>

app/views/cats/_form.html.erb
<% action_url = (action == :new) ? cats_url : cat_url(cat) %>

<form action="<%=action_url%>" method="post">
    <% if action == :edit %>
        <input type="hidden" name="_method" value="patch">
    <% end %>

    <div>
        <label for="cat_name">Name</label>
        <input type="text" name="cat[name]" id="cat_name" value="<%=cat.name %>" >
        
    </div>
    <br>
    <div>
        <label >Sex</label>
        
        <input type="radio"  name="cat[sex]" id="cat_sex_m" value="M"  <%= cat.sex == "M" ? "checked" : ""  %>>
        <label for="cat_sex_m">Male</label>
        <input type="radio" name="cat[sex]" id="cat_sex_f" value="F" <%= cat.sex == "F" ? "checked" : ""  %>>
        <label for="cat_sex_f">Female</label>
    </div>
    <br>
    <div>
        <label for="cat_color">Color</label>
        <select name="cat[color]" id="cat_color">
            <option disabled>--Please select--</option>
            <% @colors.each do |color| %>
                <option value="<%= color%>" <%= cat.color == color ? "selected" : "" %>  > <%= color.capitalize %> </option>

            <% end %>
        </select>
    </div>
    <br>
    <div>
        <label for="cat_birth_date">Birth Date</label>
        <input type="date" id="cat_birth_date" name="cat[birth_date]" value="<%= cat.birth_date%>"  >
    </div>
    <br>
    <div>
        <label for="cat_description">Description</label>
        <br>
        <textarea name="cat[description]" id="cat_description" cols="30" rows="10"><%=cat.description %></textarea>
    </div>
    <br>

    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type="submit" value="Update Cat!">

</form>

app/views/cats/edit.html.erb
<h1>Editing: <%=@cat.name%></h1>

<%= render "form", cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<h1>Look at all these Cats! </h1>

<ul>
  <% @cats.each do |cat| %>
    <li> <%= link_to cat.name, url_for(cat)  %></li>
        <ul>
            <li> color: <%= cat.color %> </li>
            <li> age: <%= cat.age %> </li>
            <li> desc: <%= cat.description %>  </li>
        </ul>
  <% end %>
</ul>

<a href="<%= new_cat_url %>">Create new cat!</a>
<br>
<a href="<%=cat_rental_requests_url %>">See all Cat Rental Request</a>

app/views/cats/new.html.erb
<h1>Build a new cat!</h1>

<%= render "form", cat: @cat, action: :new %>

app/views/cats/show.html.erb
<h1> <%= @cat.name %> </h1>
<table>
    
    <tbody>
        
        <tr>
            <td>Age</td> 
            <td><%= @cat.age %> </td>
        </tr>
        <tr>
            <td>Color</td> 
            <td><%= @cat.color %> </td>
        </tr>
        <tr>
            <td>Sex</td> 
            <td><%= @cat.sex %> </td>
        </tr>
        <tr>
            <td>Description</td> 
            <td><%= @cat.description %> </td>
        </tr>
    </tbody>
</table>
<br><br>

<a href="<%= cats_url %>">Back to all Cats</a>
<br>
<a href="<%= edit_cat_url %>">Edit this Cat</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nintyninecats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>